language: python
python:
- '2.7'
install:
    - pip install -r requirements.txt
    - pip install -r requirements_test.txt
    - pip install python-coveralls
script:
- source ./environment_test.sh
- py.test --cov ownership tests/ --cov-report=term --cov-report=html
after_success:
  - coveralls
