"""empty message

Revision ID: 2e5fec09053
Revises: None
Create Date: 2014-09-01 16:06:13.655715

"""

# revision identifiers, used by Alembic.
revision = '2e5fec09053'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('owners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title_number', sa.String(), nullable=False),
    sa.Column('lrid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('owner_index', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('owners')
    ### end Alembic commands ###
