"""empty message

Revision ID: 3a2390239c65
Revises: 25cb980c6f1b
Create Date: 2014-08-29 10:21:24.993215

"""

# revision identifiers, used by Alembic.
revision = '3a2390239c65'
down_revision = '25cb980c6f1b'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roles_users')
    op.drop_table('checks')
    op.drop_table('casework')
    op.drop_table('role')
    op.drop_table('users')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), server_default="nextval('users_id_seq'::regclass)", nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('confirmed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'users_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('role',
    sa.Column('id', sa.INTEGER(), server_default="nextval('role_id_seq'::regclass)", nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'role_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('casework',
    sa.Column('id', sa.INTEGER(), server_default="nextval('casework_id_seq'::regclass)", nullable=False),
    sa.Column('title_number', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('submitted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('application_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=u'casework_pkey')
    )
    op.create_table('checks',
    sa.Column('id', sa.INTEGER(), server_default="nextval('checks_id_seq'::regclass)", nullable=False),
    sa.Column('title_number', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('submitted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('application_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=u'checks_pkey')
    )
    op.create_table('roles_users',
    sa.Column('users_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['role_id'], [u'role.id'], name=u'roles_users_role_id_fkey'),
    sa.ForeignKeyConstraint(['users_id'], [u'users.id'], name=u'roles_users_users_id_fkey')
    )
    ### end Alembic commands ###
