"""empty message

Revision ID: 3b911bd048a8
Revises: 3a2390239c65
Create Date: 2014-08-29 13:52:16.375620

"""

# revision identifiers, used by Alembic.
revision = '3b911bd048a8'
down_revision = '3a2390239c65'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('owners', 'lrid',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('owners', 'owner_index',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('owners', 'title_number',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('owners', 'title_number',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('owners', 'owner_index',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('owners', 'lrid',
               existing_type=sa.VARCHAR(),
               nullable=True)
    ### end Alembic commands ###
