"""empty message

Revision ID: 4c47d3b71e66
Revises: None
Create Date: 2014-08-29 17:01:28.188011

"""

# revision identifiers, used by Alembic.
revision = '4c47d3b71e66'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('owners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title_number', sa.String(), nullable=True),
    sa.Column('lrid', sa.String(), nullable=True),
    sa.Column('owner_index', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('owners')
    ### end Alembic commands ###
